refactor: frontend
casper-network/casper-blockexplorer pull request #113
Opened 2022-12-16 13:32 UTC by gyroflaw

Fix Refactor Frontend #112
### 🔥 Summary

### 😤 Problem / Goals
-

### 🤓 Solution
- Revert  and use react-app-rewired to make simple
- Replace emotion with styled-component

### 🗒️ Additional Notes
-

2022-12-19 13:56 UTC, hoffmannjan commented
Just did a overall look but I'm not sure do we want to revert `eject` now. @DorianKwan any opinions?

2022-12-19 18:24 UTC, DorianKwan commented
I'm confused why we are reverting back to CRA setup.  We are losing control of a large set of configuration that doesn't lend well to the maintenance and development of a production application.

I don't believe reverting the the eject is the way to go.

For context, we ejected with the long term goal of stripping away all CRA setup in favour of a more custom setup.  We didn't have the time to remove it completely yet.  And that's what led us to today.  Where the eject doesn't seem like it's worth it at the moment in favour of rewired.  But the decision to not use rewired has previously been made.

Can you expand on your idea of using rewired instead?

2022-12-19 18:51 UTC, DorianKwan requested changes

2022-12-19 18:51 UTC, DorianKwan commented on frontend/.eslintrc.js
> +  extends: ['react-app', 'react-app/jest', 'prettier'],
There is also a plan in the future to create our own package to keep eslint configurations consistent project to project.  Let's not change this completely.  If you want to add or change a few rules let's chat about that.

2022-12-19 18:51 UTC, DorianKwan commented on frontend/src/components/base/Button/Button.test.tsx
> +    const button = screen.getByRole('button', { name: 'button' });
Is there any concerns here with not using the method off of the custom render?

2022-12-20 17:30 UTC, hoffmannjan commented
Hi @gyroflaw, for now please let's stick to ejected project. 
We can decide about this later on in January, there are too many question marks right now about project future so I don't want anybody to spend time on this. You can keep it as a branch that we can use in future.

2022-12-20 17:31 UTC, hoffmannjan commented
Oh and there are now a few conflicts because @valfaro123 added multilang support, please look at them, then you should be unlocked. Cheers :)

2023-01-04 14:12 UTC, hoffmannjan commented
@gyroflaw please revert React app eject and resolve the conflicts so we can merge it.

2023-01-04 14:26 UTC, hoffmannjan requested changes
@gyroflaw please revert React app eject and resolve the conflicts so we can merge it.

2023-01-16 07:10 UTC, closed without merging