refactor/replace tailwind with styled components
casper-network/casper-blockexplorer pull request #122
Opened 2022-12-29 16:47 UTC by valfaro123

### 🔥 Summary
-Remove tailwind and replace with styled components to fit the rest of the app

### 😤 Problem / Goals
-We have started the transition from using tailwind to styled components
-The app currently has some components that need to be converted 

### 🤓 Solution
-Replace old tailwind classes with styled components

2022-12-29 17:31 UTC, Thistle-Strum commented on frontend/src/components/layout/PageWrapper/PageWrapper.tsx
> +    padding: 0 ${pxToRem(48)};
These breakpoint pixel values can be replaced with the breakpoints obj in styled-theme.ts

2022-12-29 17:32 UTC, Thistle-Strum commented on frontend/src/components/tables/LatestBlocks/LatestBlocks.tsx
> +  font-weight: 500;
Font weights are also in styled-theme

2022-12-29 17:40 UTC, Thistle-Strum commented on frontend/src/components/tables/BlockTable/BlockTable.tsx
> +  font-weight: 500;
${fontWeight.medium}

2022-12-29 17:41 UTC, Thistle-Strum commented on frontend/src/components/tables/BlockTable/BlockTable.tsx
> +  font-weight: bold;
`${fontWeight.bold}`

2022-12-29 17:42 UTC, Thistle-Strum commented on frontend/src/components/tables/LatestBlocks/LatestBlocks.tsx
> +  font-weight: bold;
`${fontWeight.bold}`

2022-12-29 17:42 UTC, Thistle-Strum commented on frontend/src/components/tables/PeerTable/PeerTable.tsx
> +  font-weight: bold;
`${fontWeight.bold}`

2022-12-29 20:17 UTC, Thistle-Strum approved these changes

2023-01-03 15:04 UTC, hoffmannjan requested changes
After removing all of the tailwind imports / dependencies a few things broke - here are screenshots:
<img width="1642" alt="Screenshot 2023-01-03 at 16 02 57" src="https://user-images.githubusercontent.com/3756160/210383868-ba47b793-3290-4704-8251-67514c60be06.png">

<img width="1840" alt="screenshot_2023-01-03_at_16 02 33" src="https://user-images.githubusercontent.com/3756160/210383952-9c6eeff5-fd01-45bb-8b59-fc0bdff35930.png">

so please go through the views and make sure all is complete :) 

other then this LGTM!

2023-01-04 13:32 UTC, hoffmannjan approved these changes
OK I helped with conflicts and updated few things, looking good, only problem is that it now fails on the tests, @Thistle-Strum could you look at this?

2023-01-04 17:48 UTC, merged