Feat/361/add UI kit copy to clipboard
casper-network/casper-blockexplorer pull request #386
Opened 2023-06-09 16:18 UTC by valfaro123

### 🔥 Summary
- Replace CopyToClipboard component with ui-kit component for #361 

### 😤 Problem / Goals
- We have moved the CopyToClipboard component into the casper-ui-kit 

### 🤓 Solution
- Remove the old component and update it with ui-kit

2023-06-09 16:35 UTC, Thistle-Strum approved these changes

2023-06-09 16:53 UTC, mgibson-casper approved these changes

2023-06-13 15:09 UTC, DorianKwan requested changes

2023-06-13 15:09 UTC, DorianKwan commented on app/src/components/utility/StyledCopyToClipboard/StyledCopyToClipboard.tsx
> +  textToCopy: string;
```suggestion
  readonly textToCopy: string;
```

2023-06-13 15:09 UTC, DorianKwan commented on app/src/components/utility/index.ts
> -export { CopyToClipboard } from './CopyToClipboard';
Can we replace this with the styled CopyToClipboard export?  And then clean up 
`import ... from 'src/components/utility/StyledCopyToClipboard';` to `import ... from 'src/components/utility';`

2023-06-13 15:10 UTC, mgibson-casper approved these changes
Nice work 👍

2023-06-13 15:18 UTC, DorianKwan approved these changes
Awesome!

2023-06-13 15:21 UTC, merged